name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Используем актуальную версию, чтобы минимизировать варнинги
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          # "yes |" заставляет билд отвечать "да" на все вопросы о лицензиях
          command: yes | buildozer android debug
          buildozer_version: master

      - name: Upload APK
        if: success() # Запускать только если сборка прошла успешно
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ${{ steps.buildozer.outputs.filename }}
